name: ColorTeleport
version: 1.1
main: com.vivio1204.hooks.colorteam.ColorTeleport
description: "Debug Plugin"
author: Vivio1204
depend: [ColorTeaming]
commands:
   colorteleport:
      description: sets config
      usage: /<command>
      permission: colorteleport.usecommand
      permission-message: You don't have <permission>
permissions:
   colorteleport.usecommand:
      description: Allows you to use commands that are provided by plugin
      usage: op
